# Generated by Django 5.1.2 on 2024-12-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_otp_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
