# Generated by Django 5.1.2 on 2025-09-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_total_price_orderitem_price'),
        ('product', '0003_product_external_id_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.size'),
        ),
    ]
