# Generated by Django 5.1.2 on 2025-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
