# Generated by Django 5.1.2 on 2025-09-06 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 7, 18, 30, 52, 146484, tzinfo=datetime.timezone.utc)),
        ),
    ]
