# Generated by Django 5.1.2 on 2025-09-07 12:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_discountcode_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 12, 23, 20, 137547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.discountcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'discount')},
            },
        ),
        migrations.AddField(
            model_name='discountcode',
            name='users',
            field=models.ManyToManyField(related_name='discount_codes', through='cart.DiscountCodeUsage', to=settings.AUTH_USER_MODEL),
        ),
    ]
