# Generated by Django 5.1.2 on 2025-09-15 19:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_discountcode_valid_until_discountcodeusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodeusage',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', through='cart.DiscountCodeUsage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 19, 56, 47, 897922, tzinfo=datetime.timezone.utc)),
        ),
    ]
