# Generated by Django 5.1.2 on 2025-09-17 15:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_discountcodeusage_order_alter_discountcode_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 15, 33, 27, 585783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_code_usage', to='cart.order'),
        ),
    ]
