# Generated by Django 5.2.16 on 2026-07-24 18:33

import cart.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_discountcode_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.discountcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Preparing'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(default=cart.models.get_default_valid_untile),
        ),
    ]
